export interface BorderPreset {
  id: string;
  label: string;
  description: string;
  emoji: string;
  // docx border options (style is OOXML string value)
  style: string;
  size: number;
  color: string;
  space: number;
  // CSS preview style for the card
  cssPreview: string;
  previewColor: string;
}

export const BORDER_PRESETS: BorderPreset[] = [
  {
    id: "none",
    label: "بدون حدود",
    description: "لا إطار حول الصفحة",
    emoji: "⬜",
    style: "none",
    size: 0,
    color: "auto",
    space: 24,
    cssPreview: "none",
    previewColor: "transparent",
  },
  {
    id: "single",
    label: "حد بسيط",
    description: "خط مستقيم أنيق",
    emoji: "🔲",
    style: "single",
    size: 8,
    color: "1A3A5C",
    space: 24,
    cssPreview: "2px solid #1A3A5C",
    previewColor: "#1A3A5C",
  },
  {
    id: "thick",
    label: "حد سميك",
    description: "إطار بارز وسميك",
    emoji: "🟦",
    style: "thick",
    size: 18,
    color: "1A3A5C",
    space: 24,
    cssPreview: "5px solid #1A3A5C",
    previewColor: "#1A3A5C",
  },
  {
    id: "double",
    label: "حد مزدوج",
    description: "خطان متوازيان",
    emoji: "🔳",
    style: "double",
    size: 8,
    color: "2C4A8A",
    space: 24,
    cssPreview: "3px double #2C4A8A",
    previewColor: "#2C4A8A",
  },
  {
    id: "wave",
    label: "حد متموج",
    description: "خط متعرج ناعم",
    emoji: "〰️",
    style: "wave",
    size: 14,
    color: "1565C0",
    space: 24,
    cssPreview: "3px solid #1565C0",
    previewColor: "#1565C0",
  },
  {
    id: "doubleWave",
    label: "متموج مزدوج",
    description: "خطان متعرجان",
    emoji: "🌊",
    style: "doubleWave",
    size: 14,
    color: "0D47A1",
    space: 24,
    cssPreview: "4px double #0D47A1",
    previewColor: "#0D47A1",
  },
  {
    id: "hearts",
    label: "قلوب",
    description: "إطار مزخرف بقلوب",
    emoji: "❤️",
    style: "hearts",
    size: 24,
    color: "auto",
    space: 24,
    cssPreview: "3px solid #C0395E",
    previewColor: "#C0395E",
  },
  {
    id: "cup",
    label: "كؤوس",
    description: "إطار مزخرف بكؤوس",
    emoji: "🏆",
    style: "cup",
    size: 24,
    color: "auto",
    space: 24,
    cssPreview: "3px solid #8B6914",
    previewColor: "#8B6914",
  },
  {
    id: "diagCross",
    label: "شبكة مائلة",
    description: "نمط شبكي مائل",
    emoji: "✴️",
    style: "diagCross",
    size: 12,
    color: "7B5C00",
    space: 24,
    cssPreview: "2px dashed #7B5C00",
    previewColor: "#7B5C00",
  },
  {
    id: "horzCross",
    label: "شبكة متقاطعة",
    description: "تقاطعات أفقية وعمودية",
    emoji: "➕",
    style: "horzCross",
    size: 12,
    color: "555555",
    space: 24,
    cssPreview: "2px dotted #555555",
    previewColor: "#555555",
  },
  {
    id: "thinThickSmallGap",
    label: "رفيع-سميك",
    description: "خط رفيع وسميك",
    emoji: "📐",
    style: "thinThickSmallGap",
    size: 12,
    color: "3A3A3A",
    space: 24,
    cssPreview: "4px solid #3A3A3A",
    previewColor: "#3A3A3A",
  },
  {
    id: "thickThinSmallGap",
    label: "سميك-رفيع",
    description: "خط سميك ثم رفيع",
    emoji: "📏",
    style: "thickThinSmallGap",
    size: 12,
    color: "2E4057",
    space: 24,
    cssPreview: "3px solid #2E4057",
    previewColor: "#2E4057",
  },
];
